capitols_list = [ ["Alabama", "Montgomery"],
                  ["Alaska", "Juneau"],
                  ["Arizona", "Phoenix"],
                  ["Arkansas", "Little Rock"],
                  ["California", "Sacramento"],
                  ["Colorado", "Denver"],
                  ["Connecticut", "Hartford"],
                  ["Delaware", "Dover"],
                  ["Florida", "Tallahassee"],
                  ["Georgia", "Atlanta"],
                  ["Hawaii", "Honolulu"],
                  ["Idaho", "Boise"],
                  ["Illinois", "Springfield"],
                  ["Indiana", "Indianapolis"],
                  ["Iowa", "Des Moines"],
                  ["Kansas", "Topeka"],
                  ["Kentucky", "Frankfort"],
                  ["Louisiana", "Baton Rouge"],
                  ["Maine", "Augusta"],
                  ["Maryland", "Annapolis"],
                  ["Massachusetts", "Boston"],
                  ["Michigan", "Lansing"],
                  ["Minnesota", "St Paul"],
                  ["Mississippi", "Jackson"],
                  ["Missouri", "Jefferson City"],
                  ["Montana", "Helena"],
                  ["Nebraska", "Lincoln"],
                  ["Nevada", "Carson City"],
                  ["New Hampshire", "Concord"],
                  ["New Jersey", "Trenton"],
                  ["New Mexico", "Santa Fe"],
                  ["New York", "Albany"],
                  ["North Carolina", "Raleigh"],
                  ["North Dakota", "Bismark"],
                  ["Ohio", "Columbus"],
                  ["Oklahoma", "Oklahoma City"],
                  ["Oregon", "Salem"],
                  ["Pennsylvania", "Harrisburg"],
                  ["Rhode Island", "Providence"],
                  ["South Carolina", "Columbia"],
                  ["South Dakota", "Pierre"],
                  ["Tennessee", "Nashville"],
                  ["Texas", "Austin"],
                  ["Utah", "Salt Lake City"],
                  ["Vermont", "Montpelier"],
                  ["Virginia", "Richmond"],
                  ["Washington", "Olympia"],
                  ["West Virginia", "Charleston"],
                  ["Wisconsin", "Madison"],
                  ["Wyoming", "Cheyenne"] ]

movies_list = [ ["Raiders of the Lost Ark", 1981],
                ["Raging Bull", 1980],
                ["E.T. the Extra-Terrestrial", 1982],
                ["The Silence of the Lambs", 1991],
                ["Goodfellas", 1990],
                ["Casablanca", 1943],
                ["Gone with the Wind", 1939],
                ["The Wizard of Oz", 1939],
                ["Tommy Boy", 1995],
                ["The Hangover", 2009],
                ["Dumb & Dumber", 1994],
                ["Fight Club", 1999],
                ["The Matrix", 1999],
                ["Toy Story", 1995],
                ["Aladdin", 1992],
                ["Finding Nemo", 1993],
                ["The Blues Brothers", 1980],
                ["Pootie Tang", 2001],
                ["The Fast and the Furious", 2001],
                ["The Godfather", 1972],
                ["Forrest Gump", 1994],
                ["Saving Private Ryan", 1998],
                ["Ferris Bueller's Day Off", 1986],
                ["The Breakfast Club", 1985],
                ["Ghostbusters", 1984],
                ["Chinatown", 1974],
                ["Star Wars", 1977],
                ["When Harry Met Sally", 1989],
                ["The Princess Bride", 1987],
                ["Jurassic Park", 1993],
                ["Titanic", 1997],
                ["Jaws", 1975],
                ["Rocky", 1976],
                ["Blazing Saddles", 1974],
                ["Space Balls", 1987],
                ["Mary Poppins", 1964],
                ["The Sound of Music", 1965],
                ["Lawrence of Arabia", 1962],
                ["The Lion King", 1994],
                ["Independence Day", 1996],
                ["Slumdog Millionaire", 2008],
                ["The Big Lebowski", 1998],
                ["Seven Samurai", 1954],
                ["Pulp Fiction", 1994],
                ["Billy Madison", 1995],
                ["Ace Ventura: Pet Detective", 1994],
                ["The Terminator", 1984],
                ["Alien", 1979],
                ["Over the Top", 1979],
                ["Point Break", 1991],
                ["Ghost", 1990],
                ["Roadhouse", 1989],
                ["Pretty Woman", 1990],
                ["The Jerk", 1979],
                ["The Fifth Element", 1997],
                ["Die Hard", 1988],
                ["Beverly Hills Cop", 1984],
                ["Monty Python and the Holy Grail", 1975],
                ["Wedding Crashers", 2005],
                ["Citizen Kane", 1941],
                ["Blade Runner", 1982],
                ["Braveheart", 1995],
                ["Teenage Mutant Ninja Turtles", 1990],
                ["Home Alone", 1990],
                ["The Notebook", 2004],
                ["The Evil Dead", 1981],
                ["The Exorcist", 1973],
                ["National Lampoon's Animal House", 1978],
                ["Space Jam", 1996],
                ["Mean Girls", 2004],
                ["Dirty Dancing", 1987],
                ["Scream 3", 2000],
                ["Moulin Rouge", 2001],
                ["Clerks", 1994],
                ["Breathless", 1960],
                ["Ronin", 1998],
                ["Snow White and the Seven Dwarfs", 1937],
                ["The Hitchhiker's Guide to the Galaxy (the one with Zooey Deschanel)", 2005],
                ["The Rock", 1996],
                ["Zoolander", 2001],
                ["Jumanji", 1995],
                ["Inception", 2010],
                ["My Best Friend's Wedding", 1997],
                ["Remember the Titans", 2000],
                ["Mallrats", 1995],
                ["Super Troopers", 2001] ]


movies = Deck.create(name: "Movies")

movies_list.each do |movie|
  movies.cards << Card.create(prompt: movie[0], solution: movie[1])
end


capitols = Deck.create(name: "State Capitols")

capitols_list.each do |capitol|
  capitols.cards << Card.create(prompt: capitol[0], solution: capitol[1])
end



players_list = [["LeBron James", "MIA"], ["Kevin Durant", "OKC"], ["Chris Paul", "LAC"], ["James Harden", "HOU"], ["Russell Westbrook", "OKC"], ["Marc Gasol", "MEM"], ["Stephen Curry", "GSW"], ["Kobe Bryant", "LAL"], ["Deron Williams", "BRK"], ["Blake Griffin", "LAC"], ["Mike Conley", "MEM"], ["George Hill", "IND"], ["Dwyane Wade", "MIA"], ["Carmelo Anthony", "NYK"], ["Serge Ibaka", "OKC"], ["Tyson Chandler", "NYK"], ["Tony Parker", "SAS"], ["David Lee", "GSW"], ["David West", "IND"], ["Chris Bosh", "MIA"], ["Paul George", "IND"], ["Brook Lopez", "BRK"], ["Al Horford", "ATL"], ["Tim Duncan", "SAS"], ["Tiago Splitter", "SAS"], ["Zach Randolph", "MEM"], ["Kenneth Faried", "DEN"], ["Al Jefferson", "UTA"], ["Dwight Howard", "LAL"], ["Paul Millsap", "UTA"], ["Ty Lawson", "DEN"], ["Thaddeus Young", "PHI"], ["Amir Johnson", "TOR"], ["Joakim Noah", "CHI"], ["LaMarcus Aldridge", "POR"], ["Danilo Gallinari", "DEN"], ["Paul Pierce", "BOS"], ["Jimmy Butler", "CHI"], ["Kevin Martin", "OKC"], ["Chandler Parsons", "HOU"], ["J.J. Hickson", "POR"], ["Thabo Sefolosha", "OKC"], ["Ersan Ilyasova", "MIL"], ["Nikola Pekovic", "MIN"], ["J.R. Smith", "NYK"], ["Ryan Anderson", "NOH"], ["Kosta Koufos", "DEN"], ["Kyle Korver", "ATL"], ["Matt Barnes", "LAC"], ["Luol Deng", "CHI"], ["Martell Webster", "WAS"], ["DeAndre Jordan", "LAC"], ["Carl Landry", "GSW"], ["Kawhi Leonard", "SAS"], ["Anthony Davis", "NOH"], ["Roy Hibbert", "IND"], ["Jeff Teague", "ATL"], ["Vince Carter", "DAL"], ["Andrei Kirilenko", "MIN"], ["Larry Sanders", "MIL"], ["Danny Green", "SAS"], ["Greg Monroe", "DET"], ["Nate Robinson", "CHI"], ["Nicolas Batum", "POR"], ["Brandon Jennings", "MIL"], ["Damian Lillard", "POR"], ["Carlos Boozer", "CHI"], ["Goran Dragic", "PHO"], ["Nikola Vucevic", "ORL"], ["Darren Collison", "DAL"], ["Kevin Garnett", "BOS"], ["Andre Iguodala", "DEN"], ["Jarrett Jack", "GSW"], ["Robin Lopez", "NOH"], ["Kyle Lowry", "TOR"], ["Omer Asik", "HOU"], ["Lance Stephenson", "IND"], ["Ray Allen", "MIA"], ["Jamal Crawford", "LAC"], ["Gordon Hayward", "UTA"], ["Jason Kidd", "NYK"], ["Jeremy Lin", "HOU"], ["Andre Miller", "DEN"], ["Kyrie Irving", "CLE"], ["Shawn Marion", "DAL"], ["Mario Chalmers", "MIA"], ["Nick Collison", "OKC"], ["Tristan Thompson", "CLE"], ["Tony Allen", "MEM"], ["Joe Johnson", "BRK"], ["Dirk Nowitzki", "DAL"], ["Isaiah Thomas", "SAC"], ["Andray Blatche", "BRK"], ["JaVale McGee", "DEN"], ["Dorell Wright", "PHI"], ["Jared Dudley", "PHO"], ["Kemba Walker", "CHA"], ["Brandon Bass", "BOS"], ["DeMar DeRozan", "TOR"], ["Jeff Green", "BOS"], ["Wesley Matthews", "POR"], ["Monta Ellis", "MIL"], ["Metta World Peace", "LAL"], ["Andre Drummond", "DET"], ["Manu Ginobili", "SAS"], ["Spencer Hawes", "PHI"], ["Emeka Okafor", "WAS"], ["John Wall", "WAS"], ["Shane Battier", "MIA"], ["DeMarcus Cousins", "SAC"], ["Boris Diaw", "SAS"], ["Mike Dunleavy", "MIL"], ["Tyreke Evans", "SAC"], ["Derrick Favors", "UTA"], ["Tyler Hansbrough", "IND"], ["Luis Scola", "PHO"], ["Reggie Evans", "BRK"], ["Antawn Jamison", "LAL"], ["Steve Nash", "LAL"], ["Luke Ridnour", "MIN"], ["Klay Thompson", "GSW"], ["Raymond Felton", "NYK"], ["O.J. Mayo", "DAL"], ["Josh Smith", "ATL"], ["Brandan Wright", "DAL"], ["Jerryd Bayless", "MEM"], ["Nene Hilario", "WAS"], ["Steve Novak", "NYK"], ["Greg Smith", "HOU"], ["Jason Terry", "BOS"], ["Corey Brewer", "DEN"], ["Jonas Valanciunas", "TOR"], ["Greivis Vasquez", "NOH"], ["C.J. Watson", "BRK"], ["Eric Bledsoe", "LAC"], ["Randy Foye", "UTA"], ["Pau Gasol", "LAL"], ["Caron Butler", "LAC"], ["Jason Thompson", "SAC"], ["Dante Cunningham", "MIN"], ["Carlos Delfino", "HOU"], ["Elton Brand", "DAL"], ["Marcin Gortat", "PHO"], ["Taj Gibson", "CHI"], ["Devin Harris", "ATL"], ["Gerald Henderson", "CHA"], ["Jrue Holiday", "PHI"], ["Courtney Lee", "BOS"], ["Udonis Haslem", "MIA"], ["Quincy Pondexter", "MEM"], ["Pablo Prigioni", "NYK"], ["Rajon Rondo", "BOS"], ["Marcus Thornton", "SAC"], ["Al-Farouq Aminu", "NOH"], ["Trevor Ariza", "WAS"], ["DeMarre Carroll", "UTA"], ["Wilson Chandler", "DEN"], ["Kirk Hinrich", "CHI"], ["Gerald Wallace", "BRK"], ["Chris Wilcox", "BOS"], ["Bradley Beal", "WAS"], ["Marco Belinelli", "CHI"], ["Jodie Meeks", "LAL"], ["Ricky Rubio", "MIN"], ["Derrick Williams", "MIN"], ["Ramon Sessions", "CHA"], ["P.J. Tucker", "PHO"], ["D.J. Augustin", "IND"], ["Harrison Barnes", "GSW"], ["Chris Andersen", "MIA"], ["Kris Humphries", "BRK"], ["Lamar Odom", "LAC"], ["Zaza Pachulia", "ATL"], ["Jared Sullinger", "BOS"], ["Ekpe Udoh", "MIL"], ["C.J. Miles", "CLE"], ["Mike Miller", "MIA"], ["Lavoy Allen", "PHI"], ["Matt Bonner", "SAS"], ["Willie Green", "LAC"], ["Reggie Jackson", "OKC"], ["Kendrick Perkins", "OKC"], ["Rodney Stuckey", "DET"], ["Steve Blake", "LAL"], ["Maurice Harkless", "ORL"], ["Meyers Leonard", "POR"], ["Louis Williams", "ATL"], ["Trevor Booker", "WAS"], ["Earl Clark", "LAL"], ["Ivan Johnson", "ATL"], ["Enes Kanter", "UTA"], ["Ian Mahinmi", "IND"], ["Kyle Singler", "DET"], ["Marvin Williams", "UTA"], ["Nick Young", "PHI"], ["Patrick Beverley", "HOU"], ["DeJuan Blair", "SAS"], ["Samuel Dalembert", "MIL"], ["A.J. Price", "WAS"], ["Brian Roberts", "NOH"], ["Chris Copeland", "NYK"], ["Michael Kidd-Gilchrist", "CHA"], ["Jameer Nelson", "ORL"], ["Evan Turner", "PHI"], ["Arron Afflalo", "ORL"], ["Jonas Jerebko", "DET"], ["Jermaine O'Neal", "PHO"], ["Tyler Zeller", "CLE"], ["Jose Barea", "MIN"], ["Alonzo Gee", "CLE"], ["John Henson", "MIL"], ["Gary Neal", "SAS"], ["Iman Shumpert", "NYK"], ["Damien Wilkins", "PHI"], ["Jason Maxiell", "DET"], ["Mo Williams", "UTA"], ["Darrell Arthur", "MEM"], ["Andrew Bogut", "GSW"], ["Will Bynum", "DET"], ["John Jenkins", "ATL"], ["Markieff Morris", "PHO"], ["Andrew Nicholson", "ORL"], ["Jason Smith", "NOH"], ["Greg Stiemsma", "MIN"], ["Alan Anderson", "TOR"], ["Chris Kaman", "DAL"], ["John Salmons", "SAC"], ["Charlie Villanueva", "DET"], ["Jae Crowder", "DAL"], ["Festus Ezeli", "GSW"], ["Mickael Gelabale", "MIN"], ["Chuck Hayes", "SAC"], ["Orlando Johnson", "IND"], ["DeShawn Stevenson", "ATL"], ["Bismack Biyombo", "CHA"], ["Keith Bogans", "BRK"], ["Roger Mason", "NOH"], ["Jason Richardson", "PHI"], ["MarShon Brooks", "BRK"], ["Nando De Colo", "SAS"], ["Gerald Green", "IND"], ["Shannon Brown", "PHO"], ["Rashard Lewis", "MIA"], ["Jeff Taylor", "CHA"], ["Garrett Temple", "WAS"], ["Anthony Tolliver", "ATL"], ["Landry Fields", "TOR"], ["Jimmer Fredette", "SAC"], ["Eric Gordon", "NOH"], ["Brandon Knight", "DET"], ["John Lucas", "TOR"], ["Jeff Adrien", "CHA"], ["Alec Burks", "UTA"], ["Chris Duhon", "LAL"], ["Royal Ivey", "PHI"], ["Leandro Barbosa", "BOS"], ["Terrence Ross", "TOR"], ["Jamaal Tinsley", "UTA"], ["Dion Waiters", "CLE"], ["Sam Young", "IND"], ["Glen Davis", "ORL"], ["Alexey Shved", "MIN"], ["Luke Walton", "CLE"], ["Cartier Martin", "WAS"], ["Donatas Motiejunas", "HOU"], ["Norris Cole", "MIA"], ["Draymond Green", "GSW"], ["Marquis Daniels", "MIL"], ["Daniel Gibson", "CLE"], ["Aaron Gray", "TOR"], ["Luc Mbah a Moute", "MIL"], ["Darius Miller", "NOH"], ["Chris Singleton", "WAS"], ["Rodrigue Beaubois", "DAL"], ["Avery Bradley", "BOS"], ["Richard Hamilton", "CHI"], ["Mike James", "DAL"], ["Jerry Stackhouse", "BRK"], ["Stephen Jackson", "SAS"], ["E'Twaun Moore", "ORL"], ["Darius Morris", "LAL"], ["Andrea Bargnani", "TOR"], ["Brendan Haywood", "CHA"], ["DeQuan Jones", "ORL"], ["Byron Mullens", "CHA"], ["Sasha Pavlovic", "POR"], ["Kevin Seraphin", "WAS"], ["Xavier Henry", "NOH"], ["Wesley Johnson", "PHO"], ["Earl Watson", "UTA"], ["Victor Claver", "POR"], ["Kendall Marshall", "PHO"], ["Ronnie Price", "POR"], ["Will Barton", "POR"], ["James Johnson", "SAC"], ["Ben Gordon", "CHA"], ["Austin Rivers", "NOH"], ["Michael Beasley", "PHO"]]

players = Deck.create(name: "Who He Play For?")

players_list.each do |player|
  players.cards << Card.create(prompt: player[0], solution: player[1])
end

